global_costmap: {

  global_frame:     /map,
  robot_base_frame: base_link,
  update_frequency: 5.0,
  static_map:       true,

  # obstacle_range:       25.0,
  # raytrace_range:       30.0,
  footprint:            [[0.6, -0.25], [0.6, 0.25], [-0.6, 0.25], [-0.6, -0.25]],
  inflater_layer: {
    inflation_radius: 20.0,
    cost_scaling_factor: 5.0
  },

  static_layer: {
    subscribe_to_updates: false
  },
  
  # inflation_radius:     20.0,
  #robot_radius: ir_of_robot,
  # cost_scaling_factor:  5.0,

  observation_sources:  laser_scan_sensor,
  laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

}