local_costmap: {

  global_frame:       odom,
  robot_base_frame:   base_link,
  update_frequency:   2.0 ,
  publish_frequency:  2.0,
  static_map:         false,
  rolling_window:     true,
  width:              15.0,
  height:             15.0,
  resolution:         0.250,

  obstacle_range:       25.0,
  raytrace_range:       30.0,
  footprint:            [[0.6, -0.25], [0.6, 0.25], [-0.6, 0.25], [-0.6, -0.25]],
  inflation_radius:     200.0,
  #robot_radius: ir_of_robot,
  cost_scaling_factor:  2.5,
  # observation_sources:  laser_scan_sensor ais_fake,
  observation_sources:  laser_scan_sensor,
  laser_scan_sensor:  {sensor_frame: base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  # ais_fake:           {sensor_frame: base_laser, data_type: LaserScan, topic: ais, marking: true, clearing: true}
  # ais_fake:           {sensor_frame: base_laser, data_type: PointCloud2, topic: ais, marking: true, clearing: true}

}